[package]
name = "webapp"
version = "0.1.0"
description = "General purpose web utilities."
authors = ["Layl <LaylConway@users.noreply.github.com>"]
license = "MIT/Apache-2.0"

[dependencies]
try_opt = "0.1.1"
